### ISSUE TITLE
Encoding/decoding with custom character sets

### ISSUE THREAD

**Issue by calh** [rubyworks/radix#12]
Hello,

This is probably a dumb/simple question, but I can't figure out how to decode a string with a custom character set.  Here's a quick example:

```ruby
1.9.3-p545 :001 > BASE62_ALPHABET = (0..9).to_a + ('a'..'z').to_a + ('A'..'Z').to_a
 => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"] 
1.9.3-p545 :002 > 809145531659995.b(62).to_s(BASE62_ALPHABET[0,62])
 => "3HLszsQsP" 
1.9.3-p545 :003 > "3HLszsQsP".b(BASE62_ALPHABET[0,62])
NoMethodError: undefined method `<' for #<Array:0x00000006559a78>
1.9.3-p545 :008 > "3HLszsQsP".b(62).to_i
 => 716130955509941 
```

What am I doing wrong here?

Thank you!

**Comment by trans** [comment]
Ha! That's a damn good question!

Well, this works at least:

```
b10 = Radix::Base.new(Radix::BASE::B10)
b10.convert("3HLszsQsP", BASE62_ALPHABET)
=> "809145531659995"
```

But you are right the convenience extensions should allow it too. I'll have to fix that.

**Comment by trans** [comment]
Ah, I missed the very last part -- you are getting a incorrect result in addition to the `undefined method` error. The incorrect result is b/c the first 10 entries in your custom character set are not strings. Change to:

```ruby
  BASE62_ALPHABET = (0..9).map{|x| x.to_s} + ('a'..'z').to_a + ('A'..'Z').to_a
```

And I think that fixes that issue. Not sure why it doesn't work without doing that. It may be treating the numbers as ASCII codes. Will have to look into it and decided what the proper behavior should be. If you have any suggestions in that regard, please let me know.

With regards to the `undefined method` error, I think I figure out the fix, so the next release should have that taken care of at least.

**Comment by calh** [comment]
Hmm, it seems to still do the same thing:

```ruby
1.9.3-p545 :001 > BASE62_ALPHABET = (0..9).map{|x| x.to_s} + ('a'..'z').to_a + ('A'..'Z').to_a
 => ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"] 
1.9.3-p545 :004 > 809145531659995.b(62).to_s(BASE62_ALPHABET[0,62])
 => "3HLszsQsP" 
1.9.3-p545 :005 > "3HLszsQsP".b(BASE62_ALPHABET[0,62])
NoMethodError: undefined method `<' for #<Array:0x00000001d33a78>
```

However, your other suggestion does seem to work fine:

```ruby
1.9.3-p545 :002 > b10 = Radix::Base.new(Radix::BASE::B10)
 => #<Radix::Base:0x00000002371bd8 @chars=["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"], @base=10, @values={"0"=>0, "1"=>1, "2"=>2, "3"=>3, "4"=>4, "5"=>5, "6"=>6, "7"=>7, "8"=>8, "9"=>9}> 
1.9.3-p545 :004 > b10.convert("3HLszsQsP", BASE62_ALPHABET)
 => "809145531659995" 
```

So I'm fine with this answer, but if you want to fix this bug that I found that would be super cool.  

Thanks!

**Comment by calh** [comment]
As a side note... I think the real thing to blame is that there seems to be no standard for the Base 62 alphabet!  And it's a crapshoot on the glyph order for each library's implementation.

**Comment by trans** [comment]
I just pushed the fix about 10 minutes ago. Might want to try again. I'll release the new gem here in a few minutes. 

Btw, you can remove a small bit of redundancy in your example with:

```
809145531659995.b(BASE62_ALPHABET[0,62]).to_s
```

Also, there is a standard base-62 built-in as `Radix::BASE::B62`. It is exactly the same array that you used expect the capital letters come before the lowercase letters b/c ASCII order. (Not quite a universal standard but it helps.)

**Comment by trans** [comment]
The gem has been pushed. Hopefully this is now all fixed and can be closed. Let me know. And thanks for reporting it!

**Comment by calh** [comment]
Works perfectly!  Thank you!
